#SQLite
spring.datasource.url=jdbc:sqlite:./database/apresenta-ia.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Configura Hibernate para n gerar DDL, apenas validar
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Flyway (Vx__)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration